version: '3'
services:
  mysql:
    restart: always
    build: ./data/mysql/
    volumes:
      - "./data/mysql/db:/var/lib/mysql"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TZ}
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
       - backend
  nginx:
    restart: always
    image: "nginx:mainline-alpine"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./data/nginx/conf:/etc/nginx/"
      - "./data/htdocs:/var/www/html"
    environment:
      TZ: "Asia/Tokyo"
    depends_on:
      - phpfpm
    links:
      - phpfpm
    networks:
       - backend
  phpfpm:
    build: ./data/phpfpm/
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - "./data/htdocs:/var/www/html"
    depends_on:
      - mysql
    links:
      - mysql
    networks:
       - backend
  host:
    build: ./data/htdocs
    environment:
      TZ: "Asia/Tokyo"
      PRJ: "app/source" # path of the cakephp project
    volumes:
      - "./data/htdocs:/root"
    ports:
      - "8765:80"
    depends_on:
      - mysql
      - phpfpm
    links:
      - mysql
      - phpfpm
    networks:
       - backend
  phpmyadmin:
    # Dockerfile
    build: ./data/phpmyadmin
    # Environment
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - MYSQL_USER=${PMA_USER}
      - MYSQL_PASSWORD=${PMA_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${PMA_ROOT_PASSWORD}
    # Mount host directory(host:container)
    volumes:
      - ./data/share/phpmyadmin:/share
    # Port forwarding(host:container)
    ports:
      - "${PMA_PORT}:80"
    networks:
       - backend
    # Container dependencies
    depends_on:
      - mysql
    # Restart
    restart: always
networks:
  backend:
    driver: bridge